name: TDR Deploy Common Utils
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: nationalarchives/tdr-github-actions/.github/workflows/sbt_release.yml@79eeb454c9b0688ce943050ac4c3d1b9e8ef6d99 # v0.0.20
    with:
      library-name: "Common utils"
    secrets:
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
